server:
  port: 8080

spring:
  application:
    name: onboard
  datasource:
    url: jdbc:postgresql://localhost:5432/sus
    username: postgres
    password: 1234@Mudar
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
